### PR TITLE
cogs.utils.github Add embed formatting for github issue webhooks

### PR DESCRIPTION
**Pull request by asher-the-thrasher**
### Description
This makes the commit channel issue embed look nicer using the forced new issues format. It uses the markdown header text `###` and makes that line a new field title and everything after the description of the new field until the next header text. This can probably be applied to prs as well but I haven't had the time to look into it yet as I will probably want to add some more formatting for prs. 

some notes:

-  from my testing, I had to use `copy.deepcopy(embed)` to copy the embed because of some weird crap and would love to take it out but that would require confirmation that it works without it which would require testing on the exact obs bot build (see below)
- I know I am adding the repository twice because if i hadn't added it twice, it would be at the top of the other fields in the embed if it was just added the first time for the briefs channel 

example: 
image

### Motivation and Context
I decided this would be nice to have after being annoyed seeing the unformatted markdown in the bot messages.

### How Has This Been Tested?
This will require brief testing on an obs bot build as I only tested it based on a copy of the relevant info on another bot. It should work correctly but testing never hurts. 

### Types of changes

 - New feature (non-breaking change which adds functionality) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] (see above) The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Can this be applied to PRs as well? Or is it already?

**Comment by asher-the-thrasher** [comment]
I made it so that it would work with prs with minimal work on purpose but I would want to add a little more for pr specific markdown elements before adding that, mainly checkboxes and bullet points. 
I was planning on looking into prs later in the week but if you would prefer adding it for prs and issues at the same time I can add the same change for prs now and then add more changes in another pr

**Comment by Fenrirthviti** [comment]
Understood, end result looks good to me!

**Comment by asher-the-thrasher** [comment]
now it works on prs too, decided may as well

**Comment by asher-the-thrasher** [comment]
This now also includes checkboxes and x emojis for the checklists, last change I hope

**Pull request merged**
